name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:1-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: cargo test --locked

      - name: Build release binary
        run: cargo build --release --locked
